apiVersion: apps/v1
kind: Deployment
metadata:
  name: salon-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: salon
  template:
    metadata:
      labels:
        app: salon
    spec:
      containers:
      - name: salon
        image: salon-service:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: salon-service
spec:
  selector:
    app: salon
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer
